spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/classdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: admin
    password: admin#
    sql-script-encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  redis:
    host: 10.10.80.30
    port: 6379
    timeout: 10s
  http:
    encoding:
      force: true
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 64
      thread-name-prefix: AVS-EXE-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: AVS-SCH-
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 35MB

server:
  port: 8066
  tomcat:
    uri-encoding: utf-8
    basedir: /Users/dongpp/tmp/tomcat

mybatis:
  type-aliases-package: cn.com.school.classinfo.model
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    cn:
      cityre:
        admin:
          mapper: debug

avs:
  api:
    api-key: 4IUFP6jkGPPNSmUUERNSn2
    city-house-http-prefix: http://api.cityhouse.cn
    cre-value-http-prefix: http://api.admin.cn
    cre-value-https-prefix: https://api.admin.cn
    cre-value-test-prefix: http://test.api.creprice.cn/
    batch-start-notify: SMS_148835071
    batch-finish-notify: SMS_157350532
  path:
    base: /Users/dongpp/tmp/avs/tenant/
    company: company/
    report-config: report-config/
    batch: batch/
    temp: temp/
    report: report/
    website: website/
