spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.80.32:3306/crevaluedb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: crevalue
    password: crevalue#
#    url: jdbc:mysql://localhost:3306/kee?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: root
    sql-script-encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  redis:
    host: 10.10.80.30
    port: 6379
    timeout: 10s
  http:
    encoding:
      force: true
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 64
      thread-name-prefix: AVS-EXE-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: AVS-SCH-
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 35MB

server:
  port: 8666
  tomcat:
    uri-encoding: utf-8

mybatis:
  type-aliases-package: cn.com.school.classinfo.model
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    cn:
      cityre:
        crevalue:
          mapper: debug

avs:
  api:
    api-key: 4IUFP6jkGPPNSmUUERNSn2
    city-house-http-prefix: http://api.cityhouse.cn
    cre-value-http-prefix: http://api.crevalue.cn
    cre-value-https-prefix: https://api.crevalue.cn
    cre-value-test-prefix: http://test.api.creprice.cn/
    user-name: cityre_sunchanglin
    password: 123456
    batch-start-notify: SMS_148835071
    batch-finish-notify: SMS_148835080
  path:
    base: /Users/dongpp/tmp/avs/tenant/
    company: company/
    report-config: report-config/
    batch: /Users/dongpp/tmp/avs/batch/
    temp: /Users/dongpp/tmp/avs/temp/
    report: /Users/dongpp/tmp/avs/report/
    website: /Users/dongpp/tmp/avs/website/
