spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school_class_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: machao123
    sql-script-encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  http:
    encoding:
      force: true
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 64
      thread-name-prefix: AVS-EXE-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: AVS-SCH-
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 35MB

server:
  port: 8066
  tomcat:
    uri-encoding: utf-8
    basedir: /Users/dongpp/tmp/tomcat

mybatis:
  type-aliases-package: cn.com.school.classinfo.model
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    cn:
      cityre:
        admin:
          mapper: debug
